version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "docker"
      - "dependencies"
    assignees:
      - "Addono"
    commit-message:
      prefix: "feat(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "GitHub Actions"
    assignees:
      - "addono"
    commit-message:
      prefix: "ci(deps):"
      
