app = 'mealie-addono'

primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 512

[build]
  # Use external Dockerfile, such that Dependatabot can be used for version-bumps
  dockerfile = "Dockerfile"

[env]
  ALLOW_SIGNUP = 'false'
  BASE_URL = 'https://recipes.aknapen.nl'
  MAX_WORKERS = '4'
  PGID = '1000'
  PUID = '1000'
  TZ = 'Europe/Berlin'
  WEB_CONCURRENCY = '2'

  ## Login configuration
  TOKEN_TIME = "87600" # 10 years ## The time in hours that a login/auth token is valid

  ## Email configuration
  SMTP_HOST = "smtp.mailersend.net"
  SMTP_PORT = "587"
  SMTP_FROM_NAME = "Mealie"
  # SMTP_FROM_EMAIL = "SECRET" ## fly secrets set SMTP_FROM_EMAIL="some-email-here"
  # SMTP_USER = "SECRET" ## fly secrets set SMTP_USER="some-user-here"
  SMTP_AUTH_STRATEGY = "TLS"
  # SMTP_PASSWORD = "SECRET" ## fly secrets set SMTP_PASSWORD="your-password-here"

  # OpenAI configuration - Targetting Gemini 2.0
  OPENAI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai/"
  OPENAI_MODEL = "gemini-2.0-flash"
  # OPENAI_API_KEY = "SECRET" ## fly secrets set OPENAI_API_KEY="your-key-here"

[[mounts]]
  source = 'mealie'
  destination = '/app/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "3GB"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = "suspend"  # Only available when not using swap
  auto_start_machines = true
  min_machines_running = 1  # Set to zero to allow all instances from being stopped
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256m'
  cpu_kind = 'shared'
  cpus = 1
